// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uvppermvkskacfwduqfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cHBlcm12a3NrYWNmd2R1cWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MjI5NzEsImV4cCI6MjA5MDQ5ODk3MX0.CBF29giEVLWULrxDBHQvJK5lPuC8P7e5ah8iDFFXALE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);